### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by JustANutshell** [vedard/sql-query-generator#3]
`sql.select("account", "*").where({email: "test@example.com"}).text`
Why does this code this:
`'SELECT * FROM account WHERE email = $1'`
and not this:
`'SELECT * FROM account WHERE email = "test@example.com"'`
?

**Comment by vedard** [comment]
This is a parameterized query, it's necessary to prevent [SQL injection](https://en.wikipedia.org/wiki/SQL_injection). The value (in your case the email) will be safely substituted by the database.

If you are working with PostgreSQL you can check this out: https://node-postgres.com/features/queries#Parameterized%20query
