### ISSUE TITLE
Escape table names?

### ISSUE THREAD

**Issue by kpeters-cbsi** [vedard/sql-query-generator#4]
Is this package capable of escaping table names at all?

**Comment by vedard** [comment]
Hello,

No, most database engines (postgres, mysql and mssql) do not support parameterized table and column names. I suggest you use strong validation if you need user-supplied input as a table name.

https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.md#defense-option-3-whitelist-input-validation
